# Generated by Django 4.2 on 2024-12-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foring', '0003_user_groups_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
